enableSecurityManager: true
contentMd5: true
cache:
  enabled: true
debug: true
webAddress: http://localhost
logPrefix: Web
gzip: true
ssl:
  port: 443
  keyStorePassword: password
  enable: false
  keyStore: 'keyStore'
verbose: false
hostname: localhost
enableSyntax: true
application:
  main: ''
port: 80
preConfigured: false
mysql:
  enabled: false
buffer:
  in: 1048576
  out: 1048576
workers: 1
disableViews: false
