version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: de.jungblut.common:thomasjungblut-common
    versions:
    - "> 1.1"
  - dependency-name: io.freefair.lombok
    versions:
    - 5.3.0
  - dependency-name: org.junit.vintage:junit-vintage-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.platform:junit-platform-launcher
    versions:
    - 1.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
