warning:
  invalid_view: 'Invalid view (''%s'') - - Constructor has to be #(String.class, Map.class)'
  ssl_not_enough_workers: SSL is enabled. It is recommended to use at least 3 worker threads ( Not Required )
  application_does_not_extend: Application '%s' does not extend ApplicationStructure.class
  caching_disabled: Caching is not enabled, this can reduce load times on bigger files!
  could_not_create_folder: Couldn't create the %s folder
  caching_enabled: Caching is enabled, beware that this increases memory usage - So keep an eye on it
debug:
  startup_step: 'Calling Startup Step: ''%s'''
  session_found: Found session (%s=%s) for request %s
  debug: '>> Debug - Ignore <<'
  connection_accepted: Connection accepted from '%s' - Handling the data!
  internal_redirect: Redirecting request to "/%s"
  session_set: Set session (%s=%s)
  client_not_accepting_gzip: The client does not accept GZIP encoding %s
  templating_engine_reacting: '%s is reacting to: %s'
  request_served: Request was served by '%s', with the type '%s'. The total length of the content was '%skB'
  request_served_status: 'Request was served with HTTP status: %s'
  cache_request_access: 'Accessing cached body: %s'
  cache_file_access: 'Accessing cached file: %s'
  templating_engine_debug_not_enabled: 'Config does not enable templates for: %s'
error:
  cannot_load_translations: Cannot load the translation file
  md5_digest_not_found: Could not load the MD5 MessageDigest Instance %s
  standalone_no_event_caller: STANDALONE = TRUE; but there is no alternate event caller set
  could_not_create_plugin_folder: Couldn't create %s - No plugins were loaded
  tick_error: Error in server ticking...
  database_session_unknown: Unknown database implementation (%s). Using a DumbSessionDatabase instead.
  database_unknown: Unknown database implementation (%s)
  account_admin_failed: Failed to create admin account
  worker_failed_handling: 'Error when handling request: %s'
info:
  waiting_for_executor_service: Waiting for the executor service to shutdown
  templating_engine_status: 'Templating language ''%s'': %s'
  validating_views: Validating Views...
  standalone_not_loading_plugins: Running as standalone, not loading plugins!
  starting_on_port: Starting the HTTP server on port %s
  server_started: The server is started
  accepting_connections_on: Accepting connections on 'http://%s
  request_log: 'Request: [Address: %s | User Agent: %s | Request String: %s | Host:
    %s | Query: %s, Post: %s]'
  application_cannot_find: Couldn't find application '%s'
  output_buffer_info: 'Output buffer size: %skb | Input buffer size: %skb'
  request_handler_dump: '> RequestHandler - Class ''%s'', Pattern: ''%s'''
  views_disabled: Skipped view loading (Disabled)
  accepting_ssl_connections_on: Accepting SSL connections on 'https://%s'
  cleared_views: Cleared views ( %s )
  loading_views: Loading views...
  initializing_location_services: Initializing location services
  mysql_init: Initalizing MySQL Connection
  shutting_down: Shutting down
  application_cannot_initiate: Couldn't initiate application '%s'
  starting_ssl_on_port: Starting the HTTPS server on port %s
  calling_event: Calling <%s> event
  disabling_plugins: Disabling all plugins
  disabled_plugin: Disabled plugin '%s'
  cmd_help_header: '# Available Commands ( Page %s/%s) '
  cmd_help_item: '> Command: /%s | Usage: %s | Description: %s '
  cmd_help_footer: '# Type ''/help %s'' to see the next page'
  creating: Creating %s...
  port_occupied: Specified port was occupied, running on %s instead!
  account_admin_created: 'Created admin account with password: "%s"'
  worker_available: 'Available workers: %s'
