views:
  less:
    filter: (\/assets\/less\/)([A-Za-z0-9]*)(.css|.less)?
    type: less
  css:
    filter: (\/style\/)([A-Za-z0-9]*)(.css)?
    type: css
  html:
    filter: (\/)([A-Za-z0-9]*)(.html)?
    type: html
    options:
      folder: ./views/html
  javscript:
    filter: (\/assets\/js\/)([A-Za-z0-9]*)(.js)?
    type: javascript
  img:
    filter: (\/assets\/img\/)([A-Za-z0-9]*)(.png|.jpg|.jpeg|.ico|.gif)?
    type: img
  favicon:
    filter: (\/)(favicon)(.ico)?
    type: img
  download:
    filter: (\/assets\/download\/)([A-Za-z0-9]*)(.zip|.txt|.pdf)?
    type: download
